name: Deploy to Amazon EKS

on:
  push:
    branches:
      - master # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REPOSITORY: student-record-api
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t student-record-api:$IMAGE_TAG .
        docker tag student-record-api:$IMAGE_TAG 945352217126.dkr.ecr.eu-north-1.amazonaws.com/student-record-api:$IMAGE_TAG
        docker push 945352217126.dkr.ecr.eu-north-1.amazonaws.com/student-record-api:$IMAGE_TAG

    - name: Update Kubernetes deployment on EKS
      env:
        ECR_REPOSITORY: student-record-api
        IMAGE_TAG: ${{ github.sha }}
      run: |
        aws eks update-kubeconfig --region eu-north-1 --name EKS-Cluster-Role
        kubectl set image deployment/web-app web-app=945352217126.dkr.ecr.eu-north-1.amazonaws.com/student-record-api:$IMAGE_TAG
